# Generated by Django 5.2.2 on 2025-07-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tickers', models.TextField()),
                ('expected_return', models.FloatField()),
                ('std_deviation', models.FloatField()),
                ('sharpe_ratio', models.FloatField()),
                ('treynor_ratio', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
